---

- name: CONFIG - Generate Apt Config
  template:
    src: apt-conf.j2
    dest: '/etc/apt/apt.conf.d/{{ item.key }}'
    owner: root
    group: root
    mode: '0644'
  with_dict: "{{ apt_config|default({}) }}"
