---

- name: TRANSPORT - Install apt-transport-spacewalk Package
  apt: name='apt-transport-spacewalk={{ apt_transport_spacewalk_version }}*' state=present
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'
  when: (apt_transport_spacewalk_version is defined) and (apt_transport_spacewalk_version is not none)

- name: TRANSPORT - Install Latest apt-transport-spacewalk Package
  apt: name='apt-transport-spacewalk' state=latest
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'
  when: apt_transport_spacewalk_version is not defined
